title: Mayank Sethi
logo: /assets/img/personal.png
description: A machine learning and software development professional.
google_analytics:
theme: jekyll-theme-minimal
github:
  is_user_page: true
Resume: true
Linkedin: true
